<?php

$mapel = array(
	array(
		'no' => '1',
		'hari' => 'Jumat, 29 Maret 2019',
		'pukul' => '07.00 - 09.00',
		'ap' => 'PAI',
		'pm' => 'PAI',
		'rpl' => 'PAI',
		'tsm' => 'PAI',
	),
	array(
		'no' => '1',
		'hari' => 'Jumat, 29 Maret 2019',
		'pukul' => '09.30 - 11.30',
		'ap' => 'PKN',
		'pm' => 'PKN',
		'rpl' => 'PKN',
		'tsm' => 'PKN',
	),
	array(
		'no' => '2',
		'hari' => 'Senin, 1 April 2019',
		'pukul' => '07.30 - 09.30',
		'ap' => 'BAHASA INDONESIA',
		'pm' => 'BAHASA INDONESIA',
		'rpl' => 'BAHASA INDONESIA',
		'tsm' => 'BAHASA INDONESIA',
	),
	array(
		'no' => '2',
		'hari' => 'Senin, 1 April 2019',
		'pukul' => '10.00 - 12.00',
		'ap' => 'SENI BUDAYA',
		'pm' => 'SENI BUDAYA',
		'rpl' => 'SENI BUDAYA',
		'tsm' => 'SENI BUDAYA',
	),
	array(
		'no' => '3',
		'hari' => 'Selasa, 2 April 2019',
		'pukul' => '07.30 - 09.30',
		'ap' => 'BAHASA INGGRIS',
		'pm' => 'BAHASA INGGRIS',
		'rpl' => 'BAHASA INGGRIS',
		'tsm' => 'BAHASA INGGRIS',
	),
	array(
		'no' => '3',
		'hari' => 'Selasa, 2 April 2019',
		'pukul' => '10.00 - 12.00',
		'ap' => 'PJOK',
		'pm' => 'PJOK',
		'rpl' => 'PJOK',
		'tsm' => 'PJOK',
	),
	array(
		'no' => '4',
		'hari' => 'Kamis, 4 April 2019',
		'pukul' => '07.30 - 09.30',
		'ap' => 'MATEMATIKA',
		'pm' => 'MATEMATIKA',
		'rpl' => 'MATEMATIKA',
		'tsm' => 'MATEMATIKA',
	),
	array(
		'no' => '4',
		'hari' => 'Kamis, 4 April 2019',
		'pukul' => '10.00 - 12.00',
		'ap' => 'IPS',
		'pm' => 'IPS',
		'rpl' => 'IPS',
		'tsm' => 'IPS',
	),
	array(
		'no' => '5',
		'hari' => 'Jumat, 5 April 2019',
		'pukul' => '07.00 - 09.00',
		'ap' => 'DASAR KOMPETENSI KEJURUAN',
		'pm' => 'DASAR KOMPETENSI KEJURUAN',
		'rpl' => 'DASAR KOMPETENSI KEJURUAN',
		'tsm' => 'DASAR KOMPETENSI KEJURUAN',
	),
	array(
		'no' => '5',
		'hari' => 'Jumat, 5 April 2019',
		'pukul' => '09.30 - 11.30',
		'ap' => 'BAHASA JAWA',
		'pm' => 'BAHASA JAWA',
		'rpl' => 'BAHASA JAWA',
		'tsm' => 'BAHASA JAWA',
	),
	array(
		'no' => '8',
		'hari' => 'Senin, 8 April 2019',
		'pukul' => '07.30 - 09.30',
		'ap' => 'KKPI',
		'pm' => 'KKPI',
		'rpl' => 'KKPI',
		'tsm' => 'KKPI',
	),
	array(
		'no' => '8',
		'hari' => 'Senin, 8 April 2019',
		'pukul' => '10.00 - 12.00',
		'ap' => 'KEWIRAUSAHAAN',
		'pm' => 'KEWIRAUSAHAAN',
		'rpl' => 'KEWIRAUSAHAAN',
		'tsm' => 'KEWIRAUSAHAAN',
	),
	array(
		'no' => '9',
		'hari' => 'Selasa, 9 April 2019',
		'pukul' => '07.30 - 09.30',
		'ap' => '-',
		'pm' => '-',
		'rpl' => 'FISIKA',
		'tsm' => 'FISIKA',
	),
	array(
		'no' => '9',
		'hari' => 'Selasa, 9 April 2019',
		'pukul' => '10.00 - 12.00',
		'ap' => 'IPA',
		'pm' => 'IPA',
		'rpl' => 'IPA',
		'tsm' => 'IPA',
	),
	array(
		'no' => '10',
		'hari' => 'Rabu, 10 April 2019',
		'pukul' => '07.30 - 09.30',
		'ap' => '-',
		'pm' => '-',
		'rpl' => 'KIMIA',
		'tsm' => 'KIMIA',
	),
);